create extension if not exists pgcrypto;

create table public.game_themes (
  key text primary key,
  name text not null,
  description text not null
);

create table public.game_cards (
  id bigint generated by default as identity primary key,
  theme_key text not null references public.game_themes(key) on delete cascade,
  word text not null,
  enabled boolean not null default true,
  unique(theme_key, word)
);

create table public.rooms (
  id uuid primary key default gen_random_uuid(),
  code text not null unique check (code ~ '^[A-Z2-9]{6}$'),
  host_token uuid not null default gen_random_uuid(),
  host_player_id uuid,
  status text not null default 'lobby' check (status in ('lobby','discussion','results')),
  theme_key text not null references public.game_themes(key),
  timer_seconds integer not null default 150 check (timer_seconds between 30 and 900),
  round_number integer not null default 0,
  current_round_id uuid,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default now() + interval '6 hours'
);

create table public.players (
  id uuid primary key default gen_random_uuid(),
  room_id uuid not null references public.rooms(id) on delete cascade,
  player_token uuid not null default gen_random_uuid(),
  name text not null check (char_length(name) between 1 and 24),
  score integer not null default 0,
  imposter_count integer not null default 0,
  active boolean not null default true,
  joined_at timestamptz not null default now(),
  unique(player_token)
);

create unique index players_room_name_ci_key on public.players(room_id, lower(name)) where active;

alter table public.rooms
  add constraint rooms_host_player_fk foreign key (host_player_id) references public.players(id) on delete set null;

create table public.rounds (
  id uuid primary key default gen_random_uuid(),
  room_id uuid not null references public.rooms(id) on delete cascade,
  round_number integer not null,
  card_id bigint not null references public.game_cards(id),
  imposter_player_id uuid not null references public.players(id),
  started_at timestamptz not null default now(),
  ends_at timestamptz not null,
  status text not null default 'discussion' check (status in ('discussion','results')),
  revealed_at timestamptz,
  unique(room_id, round_number)
);

alter table public.rooms
  add constraint rooms_current_round_fk foreign key (current_round_id) references public.rounds(id) on delete set null;

create table public.votes (
  round_id uuid not null references public.rounds(id) on delete cascade,
  voter_player_id uuid not null references public.players(id) on delete cascade,
  voted_player_id uuid not null references public.players(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(round_id, voter_player_id),
  check (voter_player_id <> voted_player_id)
);

create table public.room_card_history (
  room_id uuid not null references public.rooms(id) on delete cascade,
  card_id bigint not null references public.game_cards(id) on delete cascade,
  used_at timestamptz not null default now(),
  primary key(room_id, card_id)
);

create table public.room_events (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.rooms(id) on delete cascade,
  event_type text not null,
  created_at timestamptz not null default now()
);

create index players_room_idx on public.players(room_id);
create index rounds_room_idx on public.rounds(room_id);
create index room_events_room_idx on public.room_events(room_id, id desc);
create index cards_theme_idx on public.game_cards(theme_key) where enabled;
create index room_card_history_card_idx on public.room_card_history(card_id);
create index rooms_current_round_idx on public.rooms(current_round_id);
create index rooms_host_player_idx on public.rooms(host_player_id);
create index rooms_theme_idx on public.rooms(theme_key);
create index rounds_card_idx on public.rounds(card_id);
create index rounds_imposter_idx on public.rounds(imposter_player_id);
create index votes_voted_player_idx on public.votes(voted_player_id);
create index votes_voter_player_idx on public.votes(voter_player_id);

alter table public.game_themes enable row level security;
alter table public.game_cards enable row level security;
alter table public.rooms enable row level security;
alter table public.players enable row level security;
alter table public.rounds enable row level security;
alter table public.votes enable row level security;
alter table public.room_card_history enable row level security;
alter table public.room_events enable row level security;

revoke all on public.game_themes, public.game_cards, public.rooms, public.players, public.rounds, public.votes, public.room_card_history from anon, authenticated;
revoke all on public.room_events from anon, authenticated;
grant select on public.room_events to anon, authenticated;

create policy "room events are readable" on public.room_events
for select to anon, authenticated using (true);

insert into public.game_themes(key,name,description) values
('popularPeople','Popular People','Celebrities, athletes, creators and famous personalities.'),
('mixed','Mixed','Objects, places, food, brands, games and random chaos.'),
('movies','Movies','Popular films from Hollywood, Bollywood and worldwide cinema.'),
('tollywoodMovies','Tollywood Movies','Popular Telugu-language films.'),
('tollywoodActors','Tollywood Actors','Popular Telugu actors and personalities.'),
('animals','Animals','Animals from pets and wildlife to ocean creatures.'),
('moviesTv','Movies & TV Shows','A mix of movies, series, sitcoms and animated shows.');
