insert into public.game_cards(theme_key,word) values ('popularPeople','Shah Rukh Khan');
insert into public.game_cards(theme_key,word) values ('popularPeople','Salman Khan');
insert into public.game_cards(theme_key,word) values ('popularPeople','Aamir Khan');
insert into public.game_cards(theme_key,word) values ('popularPeople','Amitabh Bachchan');
insert into public.game_cards(theme_key,word) values ('popularPeople','Deepika Padukone');
insert into public.game_cards(theme_key,word) values ('popularPeople','Priyanka Chopra');
insert into public.game_cards(theme_key,word) values ('popularPeople','Ranbir Kapoor');
insert into public.game_cards(theme_key,word) values ('popularPeople','Alia Bhatt');
insert into public.game_cards(theme_key,word) values ('popularPeople','Hrithik Roshan');
insert into public.game_cards(theme_key,word) values ('popularPeople','Akshay Kumar');
insert into public.game_cards(theme_key,word) values ('popularPeople','Katrina Kaif');
insert into public.game_cards(theme_key,word) values ('popularPeople','Kareena Kapoor');
insert into public.game_cards(theme_key,word) values ('popularPeople','Rajinikanth');
insert into public.game_cards(theme_key,word) values ('popularPeople','Kamal Haasan');
insert into public.game_cards(theme_key,word) values ('popularPeople','Vijay');
insert into public.game_cards(theme_key,word) values ('popularPeople','Suriya');
insert into public.game_cards(theme_key,word) values ('popularPeople','Yash');
insert into public.game_cards(theme_key,word) values ('popularPeople','Mammootty');
insert into public.game_cards(theme_key,word) values ('popularPeople','Mohanlal');
insert into public.game_cards(theme_key,word) values ('popularPeople','Virat Kohli');
insert into public.game_cards(theme_key,word) values ('popularPeople','MS Dhoni');
insert into public.game_cards(theme_key,word) values ('popularPeople','Sachin Tendulkar');
insert into public.game_cards(theme_key,word) values ('popularPeople','Rohit Sharma');
insert into public.game_cards(theme_key,word) values ('popularPeople','Neeraj Chopra');
insert into public.game_cards(theme_key,word) values ('popularPeople','PV Sindhu');
insert into public.game_cards(theme_key,word) values ('popularPeople','Mary Kom');
insert into public.game_cards(theme_key,word) values ('popularPeople','Sania Mirza');
insert into public.game_cards(theme_key,word) values ('popularPeople','APJ Abdul Kalam');
insert into public.game_cards(theme_key,word) values ('popularPeople','Ratan Tata');
insert into public.game_cards(theme_key,word) values ('popularPeople','Mukesh Ambani');
insert into public.game_cards(theme_key,word) values ('popularPeople','Sundar Pichai');
insert into public.game_cards(theme_key,word) values ('popularPeople','Satya Nadella');
insert into public.game_cards(theme_key,word) values ('popularPeople','Elon Musk');
insert into public.game_cards(theme_key,word) values ('popularPeople','Steve Jobs');
insert into public.game_cards(theme_key,word) values ('popularPeople','Bill Gates');
insert into public.game_cards(theme_key,word) values ('popularPeople','Mark Zuckerberg');
insert into public.game_cards(theme_key,word) values ('popularPeople','Jeff Bezos');
insert into public.game_cards(theme_key,word) values ('popularPeople','Taylor Swift');
insert into public.game_cards(theme_key,word) values ('popularPeople','Ed Sheeran');
insert into public.game_cards(theme_key,word) values ('popularPeople','Justin Bieber');
insert into public.game_cards(theme_key,word) values ('popularPeople','Selena Gomez');
insert into public.game_cards(theme_key,word) values ('popularPeople','Ariana Grande');
insert into public.game_cards(theme_key,word) values ('popularPeople','Rihanna');
insert into public.game_cards(theme_key,word) values ('popularPeople','Beyonce');
insert into public.game_cards(theme_key,word) values ('popularPeople','Drake');
insert into public.game_cards(theme_key,word) values ('popularPeople','Eminem');
insert into public.game_cards(theme_key,word) values ('popularPeople','Bruno Mars');
insert into public.game_cards(theme_key,word) values ('popularPeople','Billie Eilish');
insert into public.game_cards(theme_key,word) values ('popularPeople','Lady Gaga');
insert into public.game_cards(theme_key,word) values ('popularPeople','Adele');
insert into public.game_cards(theme_key,word) values ('popularPeople','Shakira');
insert into public.game_cards(theme_key,word) values ('popularPeople','Dua Lipa');
insert into public.game_cards(theme_key,word) values ('popularPeople','The Weeknd');
insert into public.game_cards(theme_key,word) values ('popularPeople','Post Malone');
insert into public.game_cards(theme_key,word) values ('popularPeople','Nicki Minaj');
insert into public.game_cards(theme_key,word) values ('popularPeople','Travis Scott');
insert into public.game_cards(theme_key,word) values ('popularPeople','Cristiano Ronaldo');
insert into public.game_cards(theme_key,word) values ('popularPeople','Lionel Messi');
insert into public.game_cards(theme_key,word) values ('popularPeople','Neymar');
insert into public.game_cards(theme_key,word) values ('popularPeople','Kylian Mbappe');
insert into public.game_cards(theme_key,word) values ('popularPeople','David Beckham');
insert into public.game_cards(theme_key,word) values ('popularPeople','Zinedine Zidane');
insert into public.game_cards(theme_key,word) values ('popularPeople','Michael Jordan');
insert into public.game_cards(theme_key,word) values ('popularPeople','LeBron James');
insert into public.game_cards(theme_key,word) values ('popularPeople','Stephen Curry');
insert into public.game_cards(theme_key,word) values ('popularPeople','Kobe Bryant');
insert into public.game_cards(theme_key,word) values ('popularPeople','Usain Bolt');
insert into public.game_cards(theme_key,word) values ('popularPeople','Serena Williams');
insert into public.game_cards(theme_key,word) values ('popularPeople','Roger Federer');
insert into public.game_cards(theme_key,word) values ('popularPeople','Novak Djokovic');
insert into public.game_cards(theme_key,word) values ('popularPeople','Lewis Hamilton');
insert into public.game_cards(theme_key,word) values ('popularPeople','Max Verstappen');
insert into public.game_cards(theme_key,word) values ('popularPeople','Michael Phelps');
insert into public.game_cards(theme_key,word) values ('popularPeople','Simone Biles');
insert into public.game_cards(theme_key,word) values ('popularPeople','Tiger Woods');
insert into public.game_cards(theme_key,word) values ('popularPeople','John Cena');
insert into public.game_cards(theme_key,word) values ('popularPeople','The Undertaker');
insert into public.game_cards(theme_key,word) values ('popularPeople','Roman Reigns');
insert into public.game_cards(theme_key,word) values ('popularPeople','MrBeast');
insert into public.game_cards(theme_key,word) values ('popularPeople','PewDiePie');
insert into public.game_cards(theme_key,word) values ('popularPeople','IShowSpeed');
insert into public.game_cards(theme_key,word) values ('popularPeople','Kai Cenat');
insert into public.game_cards(theme_key,word) values ('popularPeople','Emma Watson');
insert into public.game_cards(theme_key,word) values ('popularPeople','Leonardo DiCaprio');
insert into public.game_cards(theme_key,word) values ('popularPeople','Tom Cruise');
insert into public.game_cards(theme_key,word) values ('popularPeople','Dwayne Johnson');
insert into public.game_cards(theme_key,word) values ('popularPeople','Johnny Depp');
insert into public.game_cards(theme_key,word) values ('popularPeople','Brad Pitt');
insert into public.game_cards(theme_key,word) values ('popularPeople','Angelina Jolie');
insert into public.game_cards(theme_key,word) values ('popularPeople','Robert Downey Jr');
insert into public.game_cards(theme_key,word) values ('popularPeople','Chris Hemsworth');
insert into public.game_cards(theme_key,word) values ('popularPeople','Chris Evans');
insert into public.game_cards(theme_key,word) values ('popularPeople','Scarlett Johansson');
insert into public.game_cards(theme_key,word) values ('popularPeople','Zendaya');
insert into public.game_cards(theme_key,word) values ('popularPeople','Tom Holland');
insert into public.game_cards(theme_key,word) values ('popularPeople','Keanu Reeves');
insert into public.game_cards(theme_key,word) values ('popularPeople','Will Smith');
insert into public.game_cards(theme_key,word) values ('popularPeople','Jackie Chan');
insert into public.game_cards(theme_key,word) values ('popularPeople','Morgan Freeman');
insert into public.game_cards(theme_key,word) values ('popularPeople','Jennifer Aniston');
