insert into public.game_cards(theme_key,word) values ('mixed','Pizza');
insert into public.game_cards(theme_key,word) values ('mixed','Biryani');
insert into public.game_cards(theme_key,word) values ('mixed','Dosa');
insert into public.game_cards(theme_key,word) values ('mixed','Burger');
insert into public.game_cards(theme_key,word) values ('mixed','Pani Puri');
insert into public.game_cards(theme_key,word) values ('mixed','Mango');
insert into public.game_cards(theme_key,word) values ('mixed','Coffee');
insert into public.game_cards(theme_key,word) values ('mixed','Chocolate');
insert into public.game_cards(theme_key,word) values ('mixed','Ice Cream');
insert into public.game_cards(theme_key,word) values ('mixed','Noodles');
insert into public.game_cards(theme_key,word) values ('mixed','Eiffel Tower');
insert into public.game_cards(theme_key,word) values ('mixed','Taj Mahal');
insert into public.game_cards(theme_key,word) values ('mixed','Mount Everest');
insert into public.game_cards(theme_key,word) values ('mixed','Dubai');
insert into public.game_cards(theme_key,word) values ('mixed','Goa');
insert into public.game_cards(theme_key,word) values ('mixed','Bengaluru');
insert into public.game_cards(theme_key,word) values ('mixed','Tokyo');
insert into public.game_cards(theme_key,word) values ('mixed','New York');
insert into public.game_cards(theme_key,word) values ('mixed','Beach');
insert into public.game_cards(theme_key,word) values ('mixed','Airport');
insert into public.game_cards(theme_key,word) values ('mixed','iPhone');
insert into public.game_cards(theme_key,word) values ('mixed','Laptop');
insert into public.game_cards(theme_key,word) values ('mixed','Headphones');
insert into public.game_cards(theme_key,word) values ('mixed','Backpack');
insert into public.game_cards(theme_key,word) values ('mixed','Umbrella');
insert into public.game_cards(theme_key,word) values ('mixed','Toothbrush');
insert into public.game_cards(theme_key,word) values ('mixed','Camera');
insert into public.game_cards(theme_key,word) values ('mixed','Mirror');
insert into public.game_cards(theme_key,word) values ('mixed','Helmet');
insert into public.game_cards(theme_key,word) values ('mixed','Water Bottle');
insert into public.game_cards(theme_key,word) values ('mixed','YouTube');
insert into public.game_cards(theme_key,word) values ('mixed','Netflix');
insert into public.game_cards(theme_key,word) values ('mixed','Instagram');
insert into public.game_cards(theme_key,word) values ('mixed','WhatsApp');
insert into public.game_cards(theme_key,word) values ('mixed','Spotify');
insert into public.game_cards(theme_key,word) values ('mixed','Google');
insert into public.game_cards(theme_key,word) values ('mixed','Amazon');
insert into public.game_cards(theme_key,word) values ('mixed','Swiggy');
insert into public.game_cards(theme_key,word) values ('mixed','Zomato');
insert into public.game_cards(theme_key,word) values ('mixed','Uber');
insert into public.game_cards(theme_key,word) values ('mixed','Minecraft');
insert into public.game_cards(theme_key,word) values ('mixed','GTA V');
insert into public.game_cards(theme_key,word) values ('mixed','Valorant');
insert into public.game_cards(theme_key,word) values ('mixed','PUBG');
insert into public.game_cards(theme_key,word) values ('mixed','Fortnite');
insert into public.game_cards(theme_key,word) values ('mixed','Among Us');
insert into public.game_cards(theme_key,word) values ('mixed','Chess');
insert into public.game_cards(theme_key,word) values ('mixed','Ludo');
insert into public.game_cards(theme_key,word) values ('mixed','Cricket');
insert into public.game_cards(theme_key,word) values ('mixed','Football');
insert into public.game_cards(theme_key,word) values ('mixed','Ferrari');
insert into public.game_cards(theme_key,word) values ('mixed','Lamborghini');
insert into public.game_cards(theme_key,word) values ('mixed','Tesla');
insert into public.game_cards(theme_key,word) values ('mixed','Royal Enfield');
insert into public.game_cards(theme_key,word) values ('mixed','Auto Rickshaw');
insert into public.game_cards(theme_key,word) values ('mixed','Metro Train');
insert into public.game_cards(theme_key,word) values ('mixed','Airplane');
insert into public.game_cards(theme_key,word) values ('mixed','Helicopter');
insert into public.game_cards(theme_key,word) values ('mixed','Bicycle');
insert into public.game_cards(theme_key,word) values ('mixed','Traffic Signal');
insert into public.game_cards(theme_key,word) values ('mixed','Moon');
insert into public.game_cards(theme_key,word) values ('mixed','Sun');
insert into public.game_cards(theme_key,word) values ('mixed','Rainbow');
insert into public.game_cards(theme_key,word) values ('mixed','Volcano');
insert into public.game_cards(theme_key,word) values ('mixed','Earthquake');
insert into public.game_cards(theme_key,word) values ('mixed','Thunderstorm');
insert into public.game_cards(theme_key,word) values ('mixed','Waterfall');
insert into public.game_cards(theme_key,word) values ('mixed','Desert');
insert into public.game_cards(theme_key,word) values ('mixed','Jungle');
insert into public.game_cards(theme_key,word) values ('mixed','Snowman');
insert into public.game_cards(theme_key,word) values ('mixed','Elephant');
insert into public.game_cards(theme_key,word) values ('mixed','Tiger');
insert into public.game_cards(theme_key,word) values ('mixed','Lion');
insert into public.game_cards(theme_key,word) values ('mixed','Panda');
insert into public.game_cards(theme_key,word) values ('mixed','Penguin');
insert into public.game_cards(theme_key,word) values ('mixed','Dolphin');
insert into public.game_cards(theme_key,word) values ('mixed','Monkey');
insert into public.game_cards(theme_key,word) values ('mixed','Dog');
insert into public.game_cards(theme_key,word) values ('mixed','Cat');
insert into public.game_cards(theme_key,word) values ('mixed','Crocodile');
insert into public.game_cards(theme_key,word) values ('mixed','Shark');
insert into public.game_cards(theme_key,word) values ('mixed','Spider-Man');
insert into public.game_cards(theme_key,word) values ('mixed','Batman');
insert into public.game_cards(theme_key,word) values ('mixed','Superman');
insert into public.game_cards(theme_key,word) values ('mixed','Iron Man');
insert into public.game_cards(theme_key,word) values ('mixed','Hulk');
insert into public.game_cards(theme_key,word) values ('mixed','Thanos');
insert into public.game_cards(theme_key,word) values ('mixed','Harry Potter');
insert into public.game_cards(theme_key,word) values ('mixed','Mr Bean');
insert into public.game_cards(theme_key,word) values ('mixed','Tom and Jerry');
insert into public.game_cards(theme_key,word) values ('mixed','Doraemon');
insert into public.game_cards(theme_key,word) values ('mixed','Shinchan');
insert into public.game_cards(theme_key,word) values ('mixed','SpongeBob');
insert into public.game_cards(theme_key,word) values ('mixed','Mickey Mouse');
insert into public.game_cards(theme_key,word) values ('mixed','Barbie');
insert into public.game_cards(theme_key,word) values ('mixed','LEGO');
insert into public.game_cards(theme_key,word) values ('mixed','Rubik''s Cube');
insert into public.game_cards(theme_key,word) values ('mixed','Birthday Cake');
insert into public.game_cards(theme_key,word) values ('mixed','Alarm Clock');
insert into public.game_cards(theme_key,word) values ('mixed','Power Bank');
