insert into public.game_cards(theme_key,word) values ('movies','Titanic');
insert into public.game_cards(theme_key,word) values ('movies','Avatar');
insert into public.game_cards(theme_key,word) values ('movies','Avengers: Endgame');
insert into public.game_cards(theme_key,word) values ('movies','Avengers: Infinity War');
insert into public.game_cards(theme_key,word) values ('movies','Iron Man');
insert into public.game_cards(theme_key,word) values ('movies','Captain America: Civil War');
insert into public.game_cards(theme_key,word) values ('movies','Thor: Ragnarok');
insert into public.game_cards(theme_key,word) values ('movies','Black Panther');
insert into public.game_cards(theme_key,word) values ('movies','Doctor Strange');
insert into public.game_cards(theme_key,word) values ('movies','Guardians of the Galaxy');
insert into public.game_cards(theme_key,word) values ('movies','Spider-Man: No Way Home');
insert into public.game_cards(theme_key,word) values ('movies','The Dark Knight');
insert into public.game_cards(theme_key,word) values ('movies','Joker');
insert into public.game_cards(theme_key,word) values ('movies','The Batman');
insert into public.game_cards(theme_key,word) values ('movies','Man of Steel');
insert into public.game_cards(theme_key,word) values ('movies','Inception');
insert into public.game_cards(theme_key,word) values ('movies','Interstellar');
insert into public.game_cards(theme_key,word) values ('movies','Tenet');
insert into public.game_cards(theme_key,word) values ('movies','Dunkirk');
insert into public.game_cards(theme_key,word) values ('movies','Oppenheimer');
insert into public.game_cards(theme_key,word) values ('movies','The Matrix');
insert into public.game_cards(theme_key,word) values ('movies','John Wick');
insert into public.game_cards(theme_key,word) values ('movies','Gladiator');
insert into public.game_cards(theme_key,word) values ('movies','The Shawshank Redemption');
insert into public.game_cards(theme_key,word) values ('movies','The Godfather');
insert into public.game_cards(theme_key,word) values ('movies','Pulp Fiction');
insert into public.game_cards(theme_key,word) values ('movies','Fight Club');
insert into public.game_cards(theme_key,word) values ('movies','Forrest Gump');
insert into public.game_cards(theme_key,word) values ('movies','Jurassic Park');
insert into public.game_cards(theme_key,word) values ('movies','Jaws');
insert into public.game_cards(theme_key,word) values ('movies','E.T.');
insert into public.game_cards(theme_key,word) values ('movies','Back to the Future');
insert into public.game_cards(theme_key,word) values ('movies','The Lion King');
insert into public.game_cards(theme_key,word) values ('movies','Toy Story');
insert into public.game_cards(theme_key,word) values ('movies','Finding Nemo');
insert into public.game_cards(theme_key,word) values ('movies','Frozen');
insert into public.game_cards(theme_key,word) values ('movies','Shrek');
insert into public.game_cards(theme_key,word) values ('movies','Kung Fu Panda');
insert into public.game_cards(theme_key,word) values ('movies','Cars');
insert into public.game_cards(theme_key,word) values ('movies','Ratatouille');
insert into public.game_cards(theme_key,word) values ('movies','Up');
insert into public.game_cards(theme_key,word) values ('movies','Coco');
insert into public.game_cards(theme_key,word) values ('movies','Inside Out');
insert into public.game_cards(theme_key,word) values ('movies','Moana');
insert into public.game_cards(theme_key,word) values ('movies','Zootopia');
insert into public.game_cards(theme_key,word) values ('movies','Despicable Me');
insert into public.game_cards(theme_key,word) values ('movies','Minions');
insert into public.game_cards(theme_key,word) values ('movies','Home Alone');
insert into public.game_cards(theme_key,word) values ('movies','Harry Potter and the Sorcerer''s Stone');
insert into public.game_cards(theme_key,word) values ('movies','The Lord of the Rings: The Fellowship of the Ring');
insert into public.game_cards(theme_key,word) values ('movies','Pirates of the Caribbean');
insert into public.game_cards(theme_key,word) values ('movies','Transformers');
insert into public.game_cards(theme_key,word) values ('movies','Mission: Impossible');
insert into public.game_cards(theme_key,word) values ('movies','Top Gun: Maverick');
insert into public.game_cards(theme_key,word) values ('movies','The Wolf of Wall Street');
insert into public.game_cards(theme_key,word) values ('movies','Catch Me If You Can');
insert into public.game_cards(theme_key,word) values ('movies','The Revenant');
insert into public.game_cards(theme_key,word) values ('movies','La La Land');
insert into public.game_cards(theme_key,word) values ('movies','Whiplash');
insert into public.game_cards(theme_key,word) values ('movies','The Social Network');
insert into public.game_cards(theme_key,word) values ('movies','Parasite');
insert into public.game_cards(theme_key,word) values ('movies','Train to Busan');
insert into public.game_cards(theme_key,word) values ('movies','Everything Everywhere All at Once');
insert into public.game_cards(theme_key,word) values ('movies','Dune');
insert into public.game_cards(theme_key,word) values ('movies','Dune: Part Two');
insert into public.game_cards(theme_key,word) values ('movies','Mad Max: Fury Road');
insert into public.game_cards(theme_key,word) values ('movies','The Hunger Games');
insert into public.game_cards(theme_key,word) values ('movies','Twilight');
insert into public.game_cards(theme_key,word) values ('movies','The Conjuring');
insert into public.game_cards(theme_key,word) values ('movies','Annabelle');
insert into public.game_cards(theme_key,word) values ('movies','It');
insert into public.game_cards(theme_key,word) values ('movies','A Quiet Place');
insert into public.game_cards(theme_key,word) values ('movies','The Hangover');
insert into public.game_cards(theme_key,word) values ('movies','Superbad');
insert into public.game_cards(theme_key,word) values ('movies','Mean Girls');
insert into public.game_cards(theme_key,word) values ('movies','Barbie');
insert into public.game_cards(theme_key,word) values ('movies','Jumanji');
insert into public.game_cards(theme_key,word) values ('movies','The Karate Kid');
insert into public.game_cards(theme_key,word) values ('movies','Rocky');
insert into public.game_cards(theme_key,word) values ('movies','Creed');
insert into public.game_cards(theme_key,word) values ('movies','Fast Five');
insert into public.game_cards(theme_key,word) values ('movies','Furious 7');
insert into public.game_cards(theme_key,word) values ('movies','3 Idiots');
insert into public.game_cards(theme_key,word) values ('movies','Dangal');
insert into public.game_cards(theme_key,word) values ('movies','PK');
insert into public.game_cards(theme_key,word) values ('movies','Lagaan');
insert into public.game_cards(theme_key,word) values ('movies','Zindagi Na Milegi Dobara');
insert into public.game_cards(theme_key,word) values ('movies','Yeh Jawaani Hai Deewani');
insert into public.game_cards(theme_key,word) values ('movies','Dilwale Dulhania Le Jayenge');
insert into public.game_cards(theme_key,word) values ('movies','Kabhi Khushi Kabhie Gham');
insert into public.game_cards(theme_key,word) values ('movies','Krrish');
insert into public.game_cards(theme_key,word) values ('movies','War');
insert into public.game_cards(theme_key,word) values ('movies','Pathaan');
insert into public.game_cards(theme_key,word) values ('movies','Jawan');
insert into public.game_cards(theme_key,word) values ('movies','Bajrangi Bhaijaan');
insert into public.game_cards(theme_key,word) values ('movies','Queen');
insert into public.game_cards(theme_key,word) values ('movies','Andhadhun');
insert into public.game_cards(theme_key,word) values ('movies','Drishyam');
insert into public.game_cards(theme_key,word) values ('movies','Gully Boy');
insert into public.game_cards(theme_key,word) values ('movies','Animal');
