insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Mayabazar');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Sankarabharanam');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Sagara Sangamam');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Swathi Muthyam');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Geethanjali');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Shiva');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Jagadeka Veerudu Athiloka Sundari');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Kshana Kshanam');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Ninne Pelladata');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Tholi Prema');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Tammudu');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Kushi');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Okkadu');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Pokiri');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Athadu');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Murari');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Arjun');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Khaleja');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Dookudu');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Businessman');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Srimanthudu');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Bharat Ane Nenu');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Maharshi');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Sarileru Neekevvaru');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Guntur Kaaram');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Indra');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Tagore');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Shankar Dada MBBS');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Stalin');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Khaidi No. 150');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Sye Raa Narasimha Reddy');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Waltair Veerayya');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Gabbar Singh');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Attarintiki Daredi');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Jalsa');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Vakeel Saab');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Bheemla Nayak');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Bro');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Arya');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Arya 2');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Julayi');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Race Gurram');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Sarrainodu');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','DJ: Duvvada Jagannadham');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Ala Vaikunthapurramuloo');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Pushpa: The Rise');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Pushpa 2: The Rule');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Magadheera');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Orange');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Racha');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Yevadu');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Dhruva');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Rangasthalam');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','RRR');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Student No. 1');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Simhadri');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Yamadonga');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Brindavanam');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Baadshah');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Temper');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Nannaku Prematho');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Janatha Garage');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Jai Lava Kusa');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Aravinda Sametha Veera Raghava');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Devara: Part 1');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Varsham');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Chatrapathi');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Billa');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Darling');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Mr. Perfect');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Mirchi');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Baahubali: The Beginning');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Baahubali 2: The Conclusion');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Saaho');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Radhe Shyam');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Salaar: Part 1 – Ceasefire');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Kalki 2898 AD');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Eega');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Maryada Ramanna');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Vedam');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Leader');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Ye Maaya Chesave');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','100% Love');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Manam');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Oopiri');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Pelli Choopulu');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Arjun Reddy');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Mahanati');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Jersey');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Agent Sai Srinivasa Athreya');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Brochevarevarura');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Jathi Ratnalu');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','DJ Tillu');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Tillu Square');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','HIT: The First Case');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','HIT: The Second Case');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Major');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Goodachari');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Kshanam');
insert into public.game_cards(theme_key,word) values ('tollywoodMovies','Fidaa');
