insert into public.game_cards(theme_key,word) values ('tollywoodActors','Chiranjeevi');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Pawan Kalyan');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Mahesh Babu');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Prabhas');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Allu Arjun');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Jr NTR');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Ram Charan');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Nani');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Ravi Teja');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Venkatesh');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Nagarjuna');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Naga Chaitanya');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Akhil Akkineni');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Vijay Deverakonda');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Ram Pothineni');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Nithiin');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Sharwanand');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Adivi Sesh');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Sree Vishnu');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Nikhil Siddhartha');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Varun Tej');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Sai Dharam Tej');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Panja Vaisshnav Tej');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Gopichand');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Manchu Vishnu');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Manchu Manoj');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Nandamuri Balakrishna');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Nandamuri Kalyan Ram');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Sudheer Babu');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Naveen Polishetty');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Siddhu Jonnalagadda');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Teja Sajja');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Kiran Abbavaram');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Bellamkonda Sreenivas');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Satyadev');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Priyadarshi');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Rahul Ramakrishna');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Sunil');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Vennela Kishore');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Brahmanandam');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Ali');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Jagapathi Babu');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Srikanth');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Rajendra Prasad');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Naresh');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Rao Ramesh');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Prakash Raj');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Sumanth');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Aadi Saikumar');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Allari Naresh');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Santosh Shoban');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Anand Deverakonda');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Vishwak Sen');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Suhas');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Nara Rohit');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Sundeep Kishan');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Aadhi Pinisetty');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Navdeep');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Tarun');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Krishna');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Krishnam Raju');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Akkineni Nageswara Rao');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','N. T. Rama Rao');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Sobhan Babu');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Samantha Ruth Prabhu');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Anushka Shetty');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Rashmika Mandanna');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Pooja Hegde');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Sai Pallavi');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Kajal Aggarwal');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Tamannaah Bhatia');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Nayanthara');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Keerthy Suresh');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Sreeleela');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Mrunal Thakur');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Krithi Shetty');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Raashi Khanna');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Rakul Preet Singh');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Shriya Saran');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Ileana D''Cruz');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Trisha Krishnan');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Genelia D''Souza');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Bhumika Chawla');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Hansika Motwani');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Anjali');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Regina Cassandra');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Eesha Rebba');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Nabha Natesh');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Nidhhi Agerwal');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Neha Shetty');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Payal Rajput');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Priyanka Jawalkar');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Ritu Varma');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Ruhani Sharma');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Aishwarya Rajesh');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Priyanka Mohan');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Shraddha Srinath');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Anupama Parameswaran');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Lavanya Tripathi');
insert into public.game_cards(theme_key,word) values ('tollywoodActors','Mehreen Pirzada');
