insert into public.game_cards(theme_key,word) values ('moviesTv','Friends');
insert into public.game_cards(theme_key,word) values ('moviesTv','Breaking Bad');
insert into public.game_cards(theme_key,word) values ('moviesTv','Game of Thrones');
insert into public.game_cards(theme_key,word) values ('moviesTv','Stranger Things');
insert into public.game_cards(theme_key,word) values ('moviesTv','Money Heist');
insert into public.game_cards(theme_key,word) values ('moviesTv','Squid Game');
insert into public.game_cards(theme_key,word) values ('moviesTv','The Office');
insert into public.game_cards(theme_key,word) values ('moviesTv','Brooklyn Nine-Nine');
insert into public.game_cards(theme_key,word) values ('moviesTv','Modern Family');
insert into public.game_cards(theme_key,word) values ('moviesTv','The Big Bang Theory');
insert into public.game_cards(theme_key,word) values ('moviesTv','How I Met Your Mother');
insert into public.game_cards(theme_key,word) values ('moviesTv','Sherlock');
insert into public.game_cards(theme_key,word) values ('moviesTv','Peaky Blinders');
insert into public.game_cards(theme_key,word) values ('moviesTv','Wednesday');
insert into public.game_cards(theme_key,word) values ('moviesTv','The Boys');
insert into public.game_cards(theme_key,word) values ('moviesTv','Dark');
insert into public.game_cards(theme_key,word) values ('moviesTv','The Witcher');
insert into public.game_cards(theme_key,word) values ('moviesTv','Narcos');
insert into public.game_cards(theme_key,word) values ('moviesTv','House of the Dragon');
insert into public.game_cards(theme_key,word) values ('moviesTv','The Last of Us');
insert into public.game_cards(theme_key,word) values ('moviesTv','Suits');
insert into public.game_cards(theme_key,word) values ('moviesTv','Dexter');
insert into public.game_cards(theme_key,word) values ('moviesTv','Lucifer');
insert into public.game_cards(theme_key,word) values ('moviesTv','Prison Break');
insert into public.game_cards(theme_key,word) values ('moviesTv','Lost');
insert into public.game_cards(theme_key,word) values ('moviesTv','Black Mirror');
insert into public.game_cards(theme_key,word) values ('moviesTv','The Crown');
insert into public.game_cards(theme_key,word) values ('moviesTv','Bridgerton');
insert into public.game_cards(theme_key,word) values ('moviesTv','Emily in Paris');
insert into public.game_cards(theme_key,word) values ('moviesTv','Sex Education');
insert into public.game_cards(theme_key,word) values ('moviesTv','Cobra Kai');
insert into public.game_cards(theme_key,word) values ('moviesTv','Better Call Saul');
insert into public.game_cards(theme_key,word) values ('moviesTv','The Walking Dead');
insert into public.game_cards(theme_key,word) values ('moviesTv','House');
insert into public.game_cards(theme_key,word) values ('moviesTv','Grey''s Anatomy');
insert into public.game_cards(theme_key,word) values ('moviesTv','Rick and Morty');
insert into public.game_cards(theme_key,word) values ('moviesTv','South Park');
insert into public.game_cards(theme_key,word) values ('moviesTv','The Simpsons');
insert into public.game_cards(theme_key,word) values ('moviesTv','Family Guy');
insert into public.game_cards(theme_key,word) values ('moviesTv','Avatar: The Last Airbender');
insert into public.game_cards(theme_key,word) values ('moviesTv','One Piece');
insert into public.game_cards(theme_key,word) values ('moviesTv','Naruto');
insert into public.game_cards(theme_key,word) values ('moviesTv','Dragon Ball Z');
insert into public.game_cards(theme_key,word) values ('moviesTv','Death Note');
insert into public.game_cards(theme_key,word) values ('moviesTv','Demon Slayer');
insert into public.game_cards(theme_key,word) values ('moviesTv','Attack on Titan');
insert into public.game_cards(theme_key,word) values ('moviesTv','Pokemon');
insert into public.game_cards(theme_key,word) values ('moviesTv','Tom and Jerry');
insert into public.game_cards(theme_key,word) values ('moviesTv','Mr Bean');
insert into public.game_cards(theme_key,word) values ('moviesTv','Doraemon');
insert into public.game_cards(theme_key,word) values ('moviesTv','Harry Potter');
insert into public.game_cards(theme_key,word) values ('moviesTv','Marvel Cinematic Universe');
insert into public.game_cards(theme_key,word) values ('moviesTv','Star Wars');
insert into public.game_cards(theme_key,word) values ('moviesTv','The Lord of the Rings');
insert into public.game_cards(theme_key,word) values ('moviesTv','Jurassic Park');
insert into public.game_cards(theme_key,word) values ('moviesTv','Fast & Furious');
insert into public.game_cards(theme_key,word) values ('moviesTv','Mission: Impossible');
insert into public.game_cards(theme_key,word) values ('moviesTv','Pirates of the Caribbean');
insert into public.game_cards(theme_key,word) values ('moviesTv','Transformers');
insert into public.game_cards(theme_key,word) values ('moviesTv','The Hunger Games');
insert into public.game_cards(theme_key,word) values ('moviesTv','Twilight');
insert into public.game_cards(theme_key,word) values ('moviesTv','John Wick');
insert into public.game_cards(theme_key,word) values ('moviesTv','Rocky');
insert into public.game_cards(theme_key,word) values ('moviesTv','Toy Story');
insert into public.game_cards(theme_key,word) values ('moviesTv','Shrek');
insert into public.game_cards(theme_key,word) values ('moviesTv','Kung Fu Panda');
insert into public.game_cards(theme_key,word) values ('moviesTv','Despicable Me');
insert into public.game_cards(theme_key,word) values ('moviesTv','Frozen');
insert into public.game_cards(theme_key,word) values ('moviesTv','Cars');
insert into public.game_cards(theme_key,word) values ('moviesTv','Finding Nemo');
insert into public.game_cards(theme_key,word) values ('moviesTv','The Lion King');
insert into public.game_cards(theme_key,word) values ('moviesTv','Spider-Man');
insert into public.game_cards(theme_key,word) values ('moviesTv','Batman');
insert into public.game_cards(theme_key,word) values ('moviesTv','Superman');
insert into public.game_cards(theme_key,word) values ('moviesTv','The Avengers');
insert into public.game_cards(theme_key,word) values ('moviesTv','Deadpool');
insert into public.game_cards(theme_key,word) values ('moviesTv','Guardians of the Galaxy');
insert into public.game_cards(theme_key,word) values ('moviesTv','Doctor Strange');
insert into public.game_cards(theme_key,word) values ('moviesTv','Black Panther');
insert into public.game_cards(theme_key,word) values ('moviesTv','Iron Man');
insert into public.game_cards(theme_key,word) values ('moviesTv','Captain America');
insert into public.game_cards(theme_key,word) values ('moviesTv','Thor');
insert into public.game_cards(theme_key,word) values ('moviesTv','Joker');
insert into public.game_cards(theme_key,word) values ('moviesTv','The Matrix');
insert into public.game_cards(theme_key,word) values ('moviesTv','Inception');
insert into public.game_cards(theme_key,word) values ('moviesTv','Interstellar');
insert into public.game_cards(theme_key,word) values ('moviesTv','Oppenheimer');
insert into public.game_cards(theme_key,word) values ('moviesTv','Barbie');
insert into public.game_cards(theme_key,word) values ('moviesTv','Titanic');
insert into public.game_cards(theme_key,word) values ('moviesTv','Avatar');
insert into public.game_cards(theme_key,word) values ('moviesTv','Dune');
insert into public.game_cards(theme_key,word) values ('moviesTv','The Conjuring');
insert into public.game_cards(theme_key,word) values ('moviesTv','Annabelle');
insert into public.game_cards(theme_key,word) values ('moviesTv','It');
insert into public.game_cards(theme_key,word) values ('moviesTv','Home Alone');
insert into public.game_cards(theme_key,word) values ('moviesTv','Jumanji');
insert into public.game_cards(theme_key,word) values ('moviesTv','Mean Girls');
insert into public.game_cards(theme_key,word) values ('moviesTv','La La Land');
insert into public.game_cards(theme_key,word) values ('moviesTv','Parasite');
insert into public.game_cards(theme_key,word) values ('moviesTv','Top Gun');
